/// Flutter icons Oratio
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Oratio
///      fonts:
///       - asset: fonts/Oratio.ttf
///
///
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
/// * Fontelico, Copyright (C) 2012 by Fontello project
///         Author:    Crowdsourced, for Fontello project
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://fontello.com
///
import 'package:flutter/widgets.dart';

class OratioIcons {
  OratioIcons._();

  static const _fontFam = 'Oratio';
  static const String? _fontPkg = null;

  static const IconData home =
      IconData(0xe800, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData apartment =
      IconData(0xe801, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData pencil =
      IconData(0xe802, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData magicWand =
      IconData(0xe803, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData drop =
      IconData(0xe804, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData lighter =
      IconData(0xe805, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData poop =
      IconData(0xe806, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData sun =
      IconData(0xe807, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData moon =
      IconData(0xe808, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData cloud =
      IconData(0xe809, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData cloudUpload =
      IconData(0xe80a, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData cloudDownload =
      IconData(0xe80b, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData cloudSync =
      IconData(0xe80c, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData cloudCheck =
      IconData(0xe80d, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData database =
      IconData(0xe80e, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData lock =
      IconData(0xe80f, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData cog =
      IconData(0xe810, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData trash =
      IconData(0xe811, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData dice =
      IconData(0xe812, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData heart =
      IconData(0xe813, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData star =
      IconData(0xe814, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData starHalf =
      IconData(0xe815, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData starEmpty =
      IconData(0xe816, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData flag =
      IconData(0xe817, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData envelope =
      IconData(0xe818, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData paperclip =
      IconData(0xe819, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData inbox =
      IconData(0xe81a, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData eye =
      IconData(0xe81b, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData printer =
      IconData(0xe81c, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData fileEmpty =
      IconData(0xe81d, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData fileAdd =
      IconData(0xe81e, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData enter =
      IconData(0xe81f, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData exit =
      IconData(0xe820, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData graduationHat =
      IconData(0xe821, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData license =
      IconData(0xe822, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData musicNote =
      IconData(0xe823, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData filmPlay =
      IconData(0xe824, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData cameraVideo =
      IconData(0xe825, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData camera =
      IconData(0xe826, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData picture =
      IconData(0xe827, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData book =
      IconData(0xe828, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData bookmark =
      IconData(0xe829, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData user =
      IconData(0xe82a, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData users =
      IconData(0xe82b, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData shirt =
      IconData(0xe82c, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData store =
      IconData(0xe82d, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData cart =
      IconData(0xe82e, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData tag =
      IconData(0xe82f, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData phoneHandset =
      IconData(0xe830, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData phone =
      IconData(0xe831, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData pushpin =
      IconData(0xe832, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData mapMaker =
      IconData(0xe833, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData spinIcon =
      IconData(0xe834, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData map =
      IconData(0xe835, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData location =
      IconData(0xe836, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData calendar =
      IconData(0xe837, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData spin =
      IconData(0xe838, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData keyboard =
      IconData(0xe839, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData spellCheck =
      IconData(0xe83a, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData screen =
      IconData(0xe83b, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData smartphone =
      IconData(0xe83c, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData tablet =
      IconData(0xe83d, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData laptop =
      IconData(0xe83e, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData laptopPhone =
      IconData(0xe83f, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData powerSwitch =
      IconData(0xe840, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData lnrbubble =
      IconData(0xe841, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData heartPulse =
      IconData(0xe842, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData construction =
      IconData(0xe843, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData pieChart =
      IconData(0xe844, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData chartBars =
      IconData(0xe845, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData gift =
      IconData(0xe846, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData diamond =
      IconData(0xe847, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData dinner =
      IconData(0xe849, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData coffeeCup =
      IconData(0xe84a, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData leaf =
      IconData(0xe84b, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData paw =
      IconData(0xe84c, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData rocket =
      IconData(0xe84d, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData briefcase =
      IconData(0xe84e, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData bus =
      IconData(0xe84f, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData car =
      IconData(0xe850, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData train =
      IconData(0xe851, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData bicycle =
      IconData(0xe852, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData wheelchair =
      IconData(0xe853, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData select =
      IconData(0xe854, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData earth =
      IconData(0xe855, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData smile =
      IconData(0xe856, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData sad =
      IconData(0xe857, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData neutral =
      IconData(0xe858, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData mustache =
      IconData(0xe859, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData alarm =
      IconData(0xe85a, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData bullhorn =
      IconData(0xe85b, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData volumeHigh =
      IconData(0xe85c, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData volumeMedium =
      IconData(0xe85d, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData volumeLow =
      IconData(0xe85e, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData volume =
      IconData(0xe85f, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData mic =
      IconData(0xe860, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData hourglass =
      IconData(0xe861, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData undo =
      IconData(0xe862, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData redo =
      IconData(0xe863, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData syncIcon =
      IconData(0xe864, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData history =
      IconData(0xe865, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData clock =
      IconData(0xe866, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData download =
      IconData(0xe867, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData upload =
      IconData(0xe868, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData enterDown =
      IconData(0xe869, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData exitUp =
      IconData(0xe86a, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData bug =
      IconData(0xe86b, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData code =
      IconData(0xe86c, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData link =
      IconData(0xe86d, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData unlink =
      IconData(0xe86e, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData thumbsUp =
      IconData(0xe86f, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData thumbsDown =
      IconData(0xe870, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData magnifier =
      IconData(0xe871, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData cross =
      IconData(0xe872, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData menu =
      IconData(0xe873, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData list =
      IconData(0xe874, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData chevronUp =
      IconData(0xe875, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData chevronDown =
      IconData(0xe876, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData chevronLeft =
      IconData(0xe877, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData chevronRight =
      IconData(0xe878, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData arrowUp =
      IconData(0xe879, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData arrowDown =
      IconData(0xe87a, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData arrowLeft =
      IconData(0xe87b, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData arrowRight =
      IconData(0xe87c, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData move =
      IconData(0xe87d, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData warning =
      IconData(0xe87e, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData menuCircle =
      IconData(0xe87f, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData questionCircle =
      IconData(0xe880, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData checkmarkCicle =
      IconData(0xe881, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData crossCircle =
      IconData(0xe882, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData plusCircle =
      IconData(0xe883, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData circleMinus =
      IconData(0xe884, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData arrowUpCicle =
      IconData(0xe885, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData arrowDownCircle =
      IconData(0xe886, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData arrowLeftCircle =
      IconData(0xe887, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData arrowRightCircle =
      IconData(0xe888, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData chevronUpCicle =
      IconData(0xe889, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData chevronDownCircle =
      IconData(0xe88a, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData chevronLeftCircle =
      IconData(0xe88b, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData chevronRightCircle =
      IconData(0xe88c, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData crop =
      IconData(0xe88d, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData layers =
      IconData(0xe88e, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData funnel =
      IconData(0xe88f, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData textFormat =
      IconData(0xe890, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData textFormatRemove =
      IconData(0xe891, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData textSize =
      IconData(0xe892, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData bold =
      IconData(0xe893, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData italic =
      IconData(0xe894, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData underline =
      IconData(0xe895, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData strikethrough =
      IconData(0xe896, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData highlight =
      IconData(0xe897, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData textAlignLeft =
      IconData(0xe898, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData textAlignCenter =
      IconData(0xe899, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData textAlignRight =
      IconData(0xe89a, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData textAlignJustify =
      IconData(0xe89b, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData lineSpacing =
      IconData(0xe89c, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData indentIncrease =
      IconData(0xe89d, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData indentDecrease =
      IconData(0xe89e, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData pilcrow =
      IconData(0xe89f, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData frameContract =
      IconData(0xe8a0, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData frameExpanded =
      IconData(0xe8a1, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData directionLtr =
      IconData(0xe8a2, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData directionRtl =
      IconData(0xe8a3, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData pageBreak =
      IconData(0xe8a4, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData sortAlphaArrow =
      IconData(0xe8a5, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData sortAmountAsc =
      IconData(0xe8a6, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData hand =
      IconData(0xe8a7, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData pointerUp =
      IconData(0xe8a8, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData pointerRight =
      IconData(0xe8a9, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData pointerDown =
      IconData(0xe8aa, fontFamily: _fontFam, fontPackage: _fontPkg);

  static const IconData pointerLeft =
      IconData(0xe8ab, fontFamily: _fontFam, fontPackage: _fontPkg);
}
